import { FunctionComponent, useState } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';

// styles
import styles from '../styles/Home.module.css'

// components
import { InputText } from '../components/Input/InputText';
import { Tag } from '../components/Tag';
import { SummaryLine } from '../components/SummaryLine';

// partials
import { Pagination } from '../components/Pagination';

interface HomePageQuery{
  page: string;
  tags: string[];
  searchQuery: string;
}

interface HomeProps{
  page: number;
  tags: string[];
  searchQuery: string;
}

const DatasetSummary: FunctionComponent = () => {
  return (
    <div className="py-4 px-4 bg-slate-100 rounded-md flex flex-col gap-y-4">
      <div>
        <Link href={`/dataset/23`}><h3 className="text-xl font-semibold">Healthcare Dataset</h3></Link>
        <p className="lg">Healthcare dataset for Sri Lanka</p>
        <div className="flex flex-row flex-wrap gap-1 py-2">
          {["Health", "Social"].map((category, i) => (
            <span key={i} className="py-1 px-2 bg-indigo-600 rounded-xl text-white text-sm">{category}</span>
          ))}
        </div>
      </div>
      <div>
        <SummaryLine 
          label="Created At"
        >
          <span>{new Date().toLocaleDateString()}</span>
        </SummaryLine>
        <SummaryLine 
          label="Last Updated"
        >
          <span>{new Date().toLocaleDateString()}</span>
        </SummaryLine>
        </div>
    </div>
  )
}

export default function Home({ page, tags, searchQuery }: HomeProps) {
  const { push } = useRouter();

  const handlePageChange = (newPage: number) => {
    push({
      query: {
        page: newPage,
        tags,
        searchQuery,
      }
    });
  };

  return (
    <>
    <div className={styles.container}>
      <Head>
        <title>Databank 🇱🇰 — Powered by WatchDog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="py-4">
        <p className={styles.description}>
        </p>
        <div className="flex flex-col">
          <InputText 
            placeholder="Start searching for datasets using keywords"
            value={searchQuery}
            onChange={(value) => {
              push({
                query: {
                  page: 0,
                  tags: [],
                  searchQuery: value,
                }
              });
            }}
          />
        </div>
        <div className="py-4">
          <div className="flex flex-row flex-wrap gap-1">
            {["Education", "Health", "Economy", "Environment", "Social"].map((category, i) => (
              <Link href="" key={i}>
                <Tag type="primary">
                  {category}
                  <span className="font-semibold">12</span>
                </Tag>
              </Link>
            ))}
          </div>
        </div>
        <div className="flex flex-col gap-2 py-4">
          {[1,2,3,4].map((item, i) => (
            <DatasetSummary key={i} />
          ))}
        </div>
        <div className="py-2">
          <Pagination 
              page={page}
              limit={10}
              count={100}
              onPageChange={handlePageChange}
          />
        </div>
      </main>
    </div>
    </>
  )
}

Home.getInitialProps = async ({ query }: { query: HomePageQuery }) => {
  const { page, tags, searchQuery} = query;

  return { page: page ? parseInt(`${page}`) : 0, tags: tags ?? [], searchQuery: searchQuery ?? "" };
}